namespace SimpleCopy
{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle6 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties45 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties46 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties47 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties48 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges14 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges15 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties49 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties50 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties51 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties52 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties53 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties54 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties55 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties56 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties57 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties58 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties59 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties60 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form1));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges11 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges12 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties41 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties42 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties43 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties44 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges13 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.bunifuDragControl1 = new Bunifu.Framework.UI.BunifuDragControl(this.components);
            this.dataGridView1 = new System.Windows.Forms.DataGridView();
            this.bunifuGroupBox1 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.bunifuFormDock1 = new Bunifu.UI.WinForms.BunifuFormDock();
            this.Channel = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.SourceChannel = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.DestinationChannel = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.Running = new System.Windows.Forms.DataGridViewCheckBoxColumn();
            this.bunifuGroupBox2 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.txtLogs = new Bunifu.UI.WinForms.BunifuTextBox();
            this.chkRunning = new Bunifu.UI.WinForms.BunifuCheckBox();
            this.btnUpdate = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnClear = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtDestinationChannel = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtSourceChannel = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtChannelEdit = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnStop = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnStart = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtTimer = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnSetTimer = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.btnMaximize = new Bunifu.UI.WinForms.BunifuImageButton();
            this.btnMinimize = new Bunifu.UI.WinForms.BunifuImageButton();
            this.btnClose = new Bunifu.UI.WinForms.BunifuImageButton();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridView1)).BeginInit();
            this.bunifuGroupBox1.SuspendLayout();
            this.bunifuGroupBox2.SuspendLayout();
            this.bunifuPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 5;
            this.bunifuElipse1.TargetControl = this;
            // 
            // bunifuDragControl1
            // 
            this.bunifuDragControl1.Fixed = true;
            this.bunifuDragControl1.Horizontal = true;
            this.bunifuDragControl1.TargetControl = this.bunifuPanel1;
            this.bunifuDragControl1.Vertical = true;
            // 
            // dataGridView1
            // 
            this.dataGridView1.AllowUserToAddRows = false;
            this.dataGridView1.AllowUserToDeleteRows = false;
            this.dataGridView1.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.dataGridView1.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            dataGridViewCellStyle5.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle5.BackColor = System.Drawing.SystemColors.Control;
            dataGridViewCellStyle5.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle5.ForeColor = System.Drawing.SystemColors.WindowText;
            dataGridViewCellStyle5.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle5.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle5.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dataGridView1.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle5;
            this.dataGridView1.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dataGridView1.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.Channel,
            this.SourceChannel,
            this.DestinationChannel,
            this.Running});
            dataGridViewCellStyle6.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle6.BackColor = System.Drawing.SystemColors.Window;
            dataGridViewCellStyle6.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle6.ForeColor = System.Drawing.SystemColors.ControlText;
            dataGridViewCellStyle6.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle6.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle6.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dataGridView1.DefaultCellStyle = dataGridViewCellStyle6;
            this.dataGridView1.GridColor = System.Drawing.SystemColors.ControlLight;
            this.dataGridView1.Location = new System.Drawing.Point(12, 163);
            this.dataGridView1.Name = "dataGridView1";
            this.dataGridView1.ReadOnly = true;
            this.dataGridView1.Size = new System.Drawing.Size(1009, 498);
            this.dataGridView1.TabIndex = 3;
            this.dataGridView1.CellMouseDoubleClick += new System.Windows.Forms.DataGridViewCellMouseEventHandler(this.dataGridView1_CellMouseDoubleClick);
            // 
            // bunifuGroupBox1
            // 
            this.bunifuGroupBox1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuGroupBox1.BorderColor = System.Drawing.Color.LightGray;
            this.bunifuGroupBox1.BorderRadius = 1;
            this.bunifuGroupBox1.BorderThickness = 1;
            this.bunifuGroupBox1.Controls.Add(this.chkRunning);
            this.bunifuGroupBox1.Controls.Add(this.btnUpdate);
            this.bunifuGroupBox1.Controls.Add(this.btnClear);
            this.bunifuGroupBox1.Controls.Add(this.txtDestinationChannel);
            this.bunifuGroupBox1.Controls.Add(this.txtSourceChannel);
            this.bunifuGroupBox1.Controls.Add(this.txtChannelEdit);
            this.bunifuGroupBox1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuGroupBox1.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuGroupBox1.LabelIndent = 10;
            this.bunifuGroupBox1.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.bunifuGroupBox1.Location = new System.Drawing.Point(12, 82);
            this.bunifuGroupBox1.Name = "bunifuGroupBox1";
            this.bunifuGroupBox1.Size = new System.Drawing.Size(1009, 75);
            this.bunifuGroupBox1.TabIndex = 6;
            this.bunifuGroupBox1.TabStop = false;
            this.bunifuGroupBox1.Text = "...";
            // 
            // bunifuFormDock1
            // 
            this.bunifuFormDock1.AllowFormDragging = true;
            this.bunifuFormDock1.AllowFormDropShadow = true;
            this.bunifuFormDock1.AllowFormResizing = true;
            this.bunifuFormDock1.AllowHidingBottomRegion = true;
            this.bunifuFormDock1.AllowOpacityChangesWhileDragging = false;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.BottomBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.LeftBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.RightBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.TopBorder.ShowBorder = true;
            this.bunifuFormDock1.ContainerControl = this;
            this.bunifuFormDock1.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
            this.bunifuFormDock1.DockingIndicatorsOpacity = 0.5D;
            this.bunifuFormDock1.DockingOptions.DockAll = true;
            this.bunifuFormDock1.DockingOptions.DockBottomLeft = true;
            this.bunifuFormDock1.DockingOptions.DockBottomRight = true;
            this.bunifuFormDock1.DockingOptions.DockFullScreen = true;
            this.bunifuFormDock1.DockingOptions.DockLeft = true;
            this.bunifuFormDock1.DockingOptions.DockRight = true;
            this.bunifuFormDock1.DockingOptions.DockTopLeft = true;
            this.bunifuFormDock1.DockingOptions.DockTopRight = true;
            this.bunifuFormDock1.FormDraggingOpacity = 0.9D;
            this.bunifuFormDock1.ParentForm = this;
            this.bunifuFormDock1.ShowCursorChanges = true;
            this.bunifuFormDock1.ShowDockingIndicators = true;
            this.bunifuFormDock1.TitleBarOptions.AllowFormDragging = true;
            this.bunifuFormDock1.TitleBarOptions.BunifuFormDock = this.bunifuFormDock1;
            this.bunifuFormDock1.TitleBarOptions.DoubleClickToExpandWindow = true;
            this.bunifuFormDock1.TitleBarOptions.TitleBarControl = null;
            this.bunifuFormDock1.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // Channel
            // 
            this.Channel.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.None;
            this.Channel.DataPropertyName = "Channel";
            this.Channel.FillWeight = 203.0457F;
            this.Channel.HeaderText = "Channel";
            this.Channel.Name = "Channel";
            this.Channel.ReadOnly = true;
            this.Channel.Width = 120;
            // 
            // SourceChannel
            // 
            this.SourceChannel.DataPropertyName = "SourceChannel";
            this.SourceChannel.FillWeight = 65.65144F;
            this.SourceChannel.HeaderText = "Source Channel";
            this.SourceChannel.Name = "SourceChannel";
            this.SourceChannel.ReadOnly = true;
            // 
            // DestinationChannel
            // 
            this.DestinationChannel.DataPropertyName = "DestinationChannel";
            this.DestinationChannel.FillWeight = 65.65144F;
            this.DestinationChannel.HeaderText = "DestinationChannel";
            this.DestinationChannel.Name = "DestinationChannel";
            this.DestinationChannel.ReadOnly = true;
            // 
            // Running
            // 
            this.Running.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.None;
            this.Running.DataPropertyName = "Running";
            this.Running.FillWeight = 65.65144F;
            this.Running.HeaderText = "Running?";
            this.Running.Name = "Running";
            this.Running.ReadOnly = true;
            this.Running.Resizable = System.Windows.Forms.DataGridViewTriState.True;
            this.Running.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.Automatic;
            this.Running.Width = 80;
            // 
            // bunifuGroupBox2
            // 
            this.bunifuGroupBox2.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuGroupBox2.BorderColor = System.Drawing.Color.LightGray;
            this.bunifuGroupBox2.BorderRadius = 1;
            this.bunifuGroupBox2.BorderThickness = 1;
            this.bunifuGroupBox2.Controls.Add(this.txtLogs);
            this.bunifuGroupBox2.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuGroupBox2.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuGroupBox2.LabelIndent = 10;
            this.bunifuGroupBox2.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.bunifuGroupBox2.Location = new System.Drawing.Point(1027, 46);
            this.bunifuGroupBox2.Name = "bunifuGroupBox2";
            this.bunifuGroupBox2.Size = new System.Drawing.Size(377, 615);
            this.bunifuGroupBox2.TabIndex = 7;
            this.bunifuGroupBox2.TabStop = false;
            this.bunifuGroupBox2.Text = "Logs";
            // 
            // txtLogs
            // 
            this.txtLogs.AcceptsReturn = false;
            this.txtLogs.AcceptsTab = false;
            this.txtLogs.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtLogs.AnimationSpeed = 200;
            this.txtLogs.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtLogs.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtLogs.BackColor = System.Drawing.Color.Transparent;
            this.txtLogs.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtLogs.BackgroundImage")));
            this.txtLogs.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtLogs.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtLogs.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtLogs.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtLogs.BorderRadius = 1;
            this.txtLogs.BorderThickness = 1;
            this.txtLogs.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtLogs.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtLogs.DefaultFont = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtLogs.DefaultText = "";
            this.txtLogs.FillColor = System.Drawing.Color.White;
            this.txtLogs.HideSelection = true;
            this.txtLogs.IconLeft = null;
            this.txtLogs.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtLogs.IconPadding = 10;
            this.txtLogs.IconRight = null;
            this.txtLogs.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtLogs.Lines = new string[0];
            this.txtLogs.Location = new System.Drawing.Point(7, 22);
            this.txtLogs.MaxLength = 32767;
            this.txtLogs.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtLogs.Modified = false;
            this.txtLogs.Multiline = true;
            this.txtLogs.Name = "txtLogs";
            stateProperties45.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties45.FillColor = System.Drawing.Color.Empty;
            stateProperties45.ForeColor = System.Drawing.Color.Empty;
            stateProperties45.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtLogs.OnActiveState = stateProperties45;
            stateProperties46.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties46.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties46.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties46.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtLogs.OnDisabledState = stateProperties46;
            stateProperties47.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties47.FillColor = System.Drawing.Color.Empty;
            stateProperties47.ForeColor = System.Drawing.Color.Empty;
            stateProperties47.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtLogs.OnHoverState = stateProperties47;
            stateProperties48.BorderColor = System.Drawing.Color.Silver;
            stateProperties48.FillColor = System.Drawing.Color.White;
            stateProperties48.ForeColor = System.Drawing.Color.Empty;
            stateProperties48.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtLogs.OnIdleState = stateProperties48;
            this.txtLogs.Padding = new System.Windows.Forms.Padding(3);
            this.txtLogs.PasswordChar = '\0';
            this.txtLogs.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtLogs.PlaceholderText = "";
            this.txtLogs.ReadOnly = false;
            this.txtLogs.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.txtLogs.SelectedText = "";
            this.txtLogs.SelectionLength = 0;
            this.txtLogs.SelectionStart = 0;
            this.txtLogs.ShortcutsEnabled = true;
            this.txtLogs.Size = new System.Drawing.Size(364, 587);
            this.txtLogs.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtLogs.TabIndex = 0;
            this.txtLogs.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtLogs.TextMarginBottom = 0;
            this.txtLogs.TextMarginLeft = 3;
            this.txtLogs.TextMarginTop = 0;
            this.txtLogs.TextPlaceholder = "";
            this.txtLogs.UseSystemPasswordChar = false;
            this.txtLogs.WordWrap = true;
            // 
            // chkRunning
            // 
            this.chkRunning.AllowBindingControlAnimation = false;
            this.chkRunning.AllowBindingControlColorChanges = false;
            this.chkRunning.AllowBindingControlLocation = false;
            this.chkRunning.AllowCheckBoxAnimation = false;
            this.chkRunning.AllowCheckmarkAnimation = false;
            this.chkRunning.AllowOnHoverStates = false;
            this.chkRunning.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.chkRunning.AutoCheck = true;
            this.chkRunning.BackColor = System.Drawing.Color.Transparent;
            this.chkRunning.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("chkRunning.BackgroundImage")));
            this.chkRunning.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.chkRunning.BindingControlPosition = Bunifu.UI.WinForms.BunifuCheckBox.BindingControlPositions.Right;
            this.chkRunning.BorderRadius = 10;
            this.chkRunning.Checked = true;
            this.chkRunning.CheckState = Bunifu.UI.WinForms.BunifuCheckBox.CheckStates.Checked;
            this.chkRunning.Cursor = System.Windows.Forms.Cursors.Default;
            this.chkRunning.CustomCheckmarkImage = null;
            this.chkRunning.Location = new System.Drawing.Point(786, 30);
            this.chkRunning.MinimumSize = new System.Drawing.Size(17, 17);
            this.chkRunning.Name = "chkRunning";
            this.chkRunning.OnCheck.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(81)))), ((int)(((byte)(137)))));
            this.chkRunning.OnCheck.BorderRadius = 10;
            this.chkRunning.OnCheck.BorderThickness = 2;
            this.chkRunning.OnCheck.CheckBoxColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(81)))), ((int)(((byte)(137)))));
            this.chkRunning.OnCheck.CheckmarkColor = System.Drawing.Color.White;
            this.chkRunning.OnCheck.CheckmarkThickness = 2;
            this.chkRunning.OnDisable.BorderColor = System.Drawing.Color.LightGray;
            this.chkRunning.OnDisable.BorderRadius = 10;
            this.chkRunning.OnDisable.BorderThickness = 2;
            this.chkRunning.OnDisable.CheckBoxColor = System.Drawing.Color.Transparent;
            this.chkRunning.OnDisable.CheckmarkColor = System.Drawing.Color.LightGray;
            this.chkRunning.OnDisable.CheckmarkThickness = 2;
            this.chkRunning.OnHoverChecked.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.chkRunning.OnHoverChecked.BorderRadius = 10;
            this.chkRunning.OnHoverChecked.BorderThickness = 2;
            this.chkRunning.OnHoverChecked.CheckBoxColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.chkRunning.OnHoverChecked.CheckmarkColor = System.Drawing.Color.White;
            this.chkRunning.OnHoverChecked.CheckmarkThickness = 2;
            this.chkRunning.OnHoverUnchecked.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.chkRunning.OnHoverUnchecked.BorderRadius = 10;
            this.chkRunning.OnHoverUnchecked.BorderThickness = 1;
            this.chkRunning.OnHoverUnchecked.CheckBoxColor = System.Drawing.Color.Transparent;
            this.chkRunning.OnUncheck.BorderColor = System.Drawing.Color.DarkGray;
            this.chkRunning.OnUncheck.BorderRadius = 10;
            this.chkRunning.OnUncheck.BorderThickness = 1;
            this.chkRunning.OnUncheck.CheckBoxColor = System.Drawing.Color.Transparent;
            this.chkRunning.Size = new System.Drawing.Size(21, 21);
            this.chkRunning.Style = Bunifu.UI.WinForms.BunifuCheckBox.CheckBoxStyles.Bunifu;
            this.chkRunning.TabIndex = 8;
            this.chkRunning.ThreeState = false;
            this.chkRunning.ToolTipText = null;
            // 
            // btnUpdate
            // 
            this.btnUpdate.AllowAnimations = true;
            this.btnUpdate.AllowMouseEffects = true;
            this.btnUpdate.AllowToggling = false;
            this.btnUpdate.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnUpdate.AnimationSpeed = 200;
            this.btnUpdate.AutoGenerateColors = false;
            this.btnUpdate.AutoRoundBorders = false;
            this.btnUpdate.AutoSizeLeftIcon = true;
            this.btnUpdate.AutoSizeRightIcon = true;
            this.btnUpdate.BackColor = System.Drawing.Color.Transparent;
            this.btnUpdate.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(81)))), ((int)(((byte)(137)))));
            this.btnUpdate.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnUpdate.BackgroundImage")));
            this.btnUpdate.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUpdate.ButtonText = "Update";
            this.btnUpdate.ButtonTextMarginLeft = 0;
            this.btnUpdate.ColorContrastOnClick = 45;
            this.btnUpdate.ColorContrastOnHover = 45;
            this.btnUpdate.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges14.BottomLeft = true;
            borderEdges14.BottomRight = true;
            borderEdges14.TopLeft = true;
            borderEdges14.TopRight = true;
            this.btnUpdate.CustomizableEdges = borderEdges14;
            this.btnUpdate.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnUpdate.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnUpdate.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnUpdate.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnUpdate.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnUpdate.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnUpdate.ForeColor = System.Drawing.Color.White;
            this.btnUpdate.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnUpdate.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnUpdate.IconLeftPadding = new System.Windows.Forms.Padding(3);
            this.btnUpdate.IconMarginLeft = 11;
            this.btnUpdate.IconPadding = 10;
            this.btnUpdate.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnUpdate.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnUpdate.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnUpdate.IconSize = 25;
            this.btnUpdate.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(81)))), ((int)(((byte)(137)))));
            this.btnUpdate.IdleBorderRadius = 5;
            this.btnUpdate.IdleBorderThickness = 1;
            this.btnUpdate.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(81)))), ((int)(((byte)(137)))));
            this.btnUpdate.IdleIconLeftImage = null;
            this.btnUpdate.IdleIconRightImage = null;
            this.btnUpdate.IndicateFocus = false;
            this.btnUpdate.Location = new System.Drawing.Point(827, 22);
            this.btnUpdate.Name = "btnUpdate";
            this.btnUpdate.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnUpdate.OnDisabledState.BorderRadius = 5;
            this.btnUpdate.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUpdate.OnDisabledState.BorderThickness = 1;
            this.btnUpdate.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnUpdate.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnUpdate.OnDisabledState.IconLeftImage = null;
            this.btnUpdate.OnDisabledState.IconRightImage = null;
            this.btnUpdate.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnUpdate.onHoverState.BorderRadius = 5;
            this.btnUpdate.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUpdate.onHoverState.BorderThickness = 1;
            this.btnUpdate.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnUpdate.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnUpdate.onHoverState.IconLeftImage = null;
            this.btnUpdate.onHoverState.IconRightImage = null;
            this.btnUpdate.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(81)))), ((int)(((byte)(137)))));
            this.btnUpdate.OnIdleState.BorderRadius = 5;
            this.btnUpdate.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUpdate.OnIdleState.BorderThickness = 1;
            this.btnUpdate.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(81)))), ((int)(((byte)(137)))));
            this.btnUpdate.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnUpdate.OnIdleState.IconLeftImage = null;
            this.btnUpdate.OnIdleState.IconRightImage = null;
            this.btnUpdate.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnUpdate.OnPressedState.BorderRadius = 5;
            this.btnUpdate.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUpdate.OnPressedState.BorderThickness = 1;
            this.btnUpdate.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnUpdate.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnUpdate.OnPressedState.IconLeftImage = null;
            this.btnUpdate.OnPressedState.IconRightImage = null;
            this.btnUpdate.Size = new System.Drawing.Size(80, 37);
            this.btnUpdate.TabIndex = 7;
            this.btnUpdate.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnUpdate.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnUpdate.TextMarginLeft = 0;
            this.btnUpdate.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnUpdate.UseDefaultRadiusAndThickness = true;
            this.btnUpdate.Click += new System.EventHandler(this.btnUpdate_Click);
            // 
            // btnClear
            // 
            this.btnClear.AllowAnimations = true;
            this.btnClear.AllowMouseEffects = true;
            this.btnClear.AllowToggling = false;
            this.btnClear.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnClear.AnimationSpeed = 200;
            this.btnClear.AutoGenerateColors = false;
            this.btnClear.AutoRoundBorders = false;
            this.btnClear.AutoSizeLeftIcon = true;
            this.btnClear.AutoSizeRightIcon = true;
            this.btnClear.BackColor = System.Drawing.Color.Transparent;
            this.btnClear.BackColor1 = System.Drawing.Color.LightGray;
            this.btnClear.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnClear.BackgroundImage")));
            this.btnClear.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClear.ButtonText = "Clear";
            this.btnClear.ButtonTextMarginLeft = 0;
            this.btnClear.ColorContrastOnClick = 45;
            this.btnClear.ColorContrastOnHover = 45;
            this.btnClear.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges15.BottomLeft = true;
            borderEdges15.BottomRight = true;
            borderEdges15.TopLeft = true;
            borderEdges15.TopRight = true;
            this.btnClear.CustomizableEdges = borderEdges15;
            this.btnClear.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnClear.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnClear.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnClear.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnClear.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnClear.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnClear.ForeColor = System.Drawing.Color.Black;
            this.btnClear.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnClear.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnClear.IconLeftPadding = new System.Windows.Forms.Padding(3);
            this.btnClear.IconMarginLeft = 11;
            this.btnClear.IconPadding = 10;
            this.btnClear.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnClear.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnClear.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnClear.IconSize = 25;
            this.btnClear.IdleBorderColor = System.Drawing.Color.LightGray;
            this.btnClear.IdleBorderRadius = 5;
            this.btnClear.IdleBorderThickness = 1;
            this.btnClear.IdleFillColor = System.Drawing.Color.LightGray;
            this.btnClear.IdleIconLeftImage = null;
            this.btnClear.IdleIconRightImage = null;
            this.btnClear.IndicateFocus = false;
            this.btnClear.Location = new System.Drawing.Point(920, 22);
            this.btnClear.Name = "btnClear";
            this.btnClear.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnClear.OnDisabledState.BorderRadius = 5;
            this.btnClear.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClear.OnDisabledState.BorderThickness = 1;
            this.btnClear.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnClear.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnClear.OnDisabledState.IconLeftImage = null;
            this.btnClear.OnDisabledState.IconRightImage = null;
            this.btnClear.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnClear.onHoverState.BorderRadius = 5;
            this.btnClear.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClear.onHoverState.BorderThickness = 1;
            this.btnClear.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnClear.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnClear.onHoverState.IconLeftImage = null;
            this.btnClear.onHoverState.IconRightImage = null;
            this.btnClear.OnIdleState.BorderColor = System.Drawing.Color.LightGray;
            this.btnClear.OnIdleState.BorderRadius = 5;
            this.btnClear.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClear.OnIdleState.BorderThickness = 1;
            this.btnClear.OnIdleState.FillColor = System.Drawing.Color.LightGray;
            this.btnClear.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnClear.OnIdleState.IconLeftImage = null;
            this.btnClear.OnIdleState.IconRightImage = null;
            this.btnClear.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnClear.OnPressedState.BorderRadius = 5;
            this.btnClear.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClear.OnPressedState.BorderThickness = 1;
            this.btnClear.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnClear.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnClear.OnPressedState.IconLeftImage = null;
            this.btnClear.OnPressedState.IconRightImage = null;
            this.btnClear.Size = new System.Drawing.Size(80, 37);
            this.btnClear.TabIndex = 6;
            this.btnClear.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnClear.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnClear.TextMarginLeft = 0;
            this.btnClear.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnClear.UseDefaultRadiusAndThickness = true;
            this.btnClear.Click += new System.EventHandler(this.bunifuButton3_Click);
            // 
            // txtDestinationChannel
            // 
            this.txtDestinationChannel.AcceptsReturn = false;
            this.txtDestinationChannel.AcceptsTab = false;
            this.txtDestinationChannel.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.txtDestinationChannel.AnimationSpeed = 200;
            this.txtDestinationChannel.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDestinationChannel.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDestinationChannel.BackColor = System.Drawing.Color.Transparent;
            this.txtDestinationChannel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDestinationChannel.BackgroundImage")));
            this.txtDestinationChannel.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtDestinationChannel.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtDestinationChannel.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDestinationChannel.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDestinationChannel.BorderRadius = 1;
            this.txtDestinationChannel.BorderThickness = 1;
            this.txtDestinationChannel.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDestinationChannel.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDestinationChannel.DefaultFont = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtDestinationChannel.DefaultText = "";
            this.txtDestinationChannel.FillColor = System.Drawing.Color.White;
            this.txtDestinationChannel.HideSelection = true;
            this.txtDestinationChannel.IconLeft = null;
            this.txtDestinationChannel.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDestinationChannel.IconPadding = 10;
            this.txtDestinationChannel.IconRight = null;
            this.txtDestinationChannel.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDestinationChannel.Lines = new string[0];
            this.txtDestinationChannel.Location = new System.Drawing.Point(471, 22);
            this.txtDestinationChannel.MaxLength = 32767;
            this.txtDestinationChannel.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtDestinationChannel.Modified = false;
            this.txtDestinationChannel.Multiline = false;
            this.txtDestinationChannel.Name = "txtDestinationChannel";
            stateProperties49.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties49.FillColor = System.Drawing.Color.Empty;
            stateProperties49.ForeColor = System.Drawing.Color.Empty;
            stateProperties49.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDestinationChannel.OnActiveState = stateProperties49;
            stateProperties50.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties50.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties50.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties50.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtDestinationChannel.OnDisabledState = stateProperties50;
            stateProperties51.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties51.FillColor = System.Drawing.Color.Empty;
            stateProperties51.ForeColor = System.Drawing.Color.Empty;
            stateProperties51.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDestinationChannel.OnHoverState = stateProperties51;
            stateProperties52.BorderColor = System.Drawing.Color.Silver;
            stateProperties52.FillColor = System.Drawing.Color.White;
            stateProperties52.ForeColor = System.Drawing.Color.Empty;
            stateProperties52.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDestinationChannel.OnIdleState = stateProperties52;
            this.txtDestinationChannel.Padding = new System.Windows.Forms.Padding(3);
            this.txtDestinationChannel.PasswordChar = '\0';
            this.txtDestinationChannel.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDestinationChannel.PlaceholderText = "Destination Channel";
            this.txtDestinationChannel.ReadOnly = false;
            this.txtDestinationChannel.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDestinationChannel.SelectedText = "";
            this.txtDestinationChannel.SelectionLength = 0;
            this.txtDestinationChannel.SelectionStart = 0;
            this.txtDestinationChannel.ShortcutsEnabled = true;
            this.txtDestinationChannel.Size = new System.Drawing.Size(301, 38);
            this.txtDestinationChannel.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtDestinationChannel.TabIndex = 5;
            this.txtDestinationChannel.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDestinationChannel.TextMarginBottom = 0;
            this.txtDestinationChannel.TextMarginLeft = 3;
            this.txtDestinationChannel.TextMarginTop = 0;
            this.txtDestinationChannel.TextPlaceholder = "Destination Channel";
            this.txtDestinationChannel.UseSystemPasswordChar = false;
            this.txtDestinationChannel.WordWrap = true;
            // 
            // txtSourceChannel
            // 
            this.txtSourceChannel.AcceptsReturn = false;
            this.txtSourceChannel.AcceptsTab = false;
            this.txtSourceChannel.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.txtSourceChannel.AnimationSpeed = 200;
            this.txtSourceChannel.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSourceChannel.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSourceChannel.BackColor = System.Drawing.Color.Transparent;
            this.txtSourceChannel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSourceChannel.BackgroundImage")));
            this.txtSourceChannel.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtSourceChannel.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtSourceChannel.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtSourceChannel.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtSourceChannel.BorderRadius = 1;
            this.txtSourceChannel.BorderThickness = 1;
            this.txtSourceChannel.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSourceChannel.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSourceChannel.DefaultFont = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtSourceChannel.DefaultText = "";
            this.txtSourceChannel.FillColor = System.Drawing.Color.White;
            this.txtSourceChannel.HideSelection = true;
            this.txtSourceChannel.IconLeft = null;
            this.txtSourceChannel.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSourceChannel.IconPadding = 10;
            this.txtSourceChannel.IconRight = null;
            this.txtSourceChannel.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSourceChannel.Lines = new string[0];
            this.txtSourceChannel.Location = new System.Drawing.Point(164, 22);
            this.txtSourceChannel.MaxLength = 32767;
            this.txtSourceChannel.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtSourceChannel.Modified = false;
            this.txtSourceChannel.Multiline = false;
            this.txtSourceChannel.Name = "txtSourceChannel";
            stateProperties53.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties53.FillColor = System.Drawing.Color.Empty;
            stateProperties53.ForeColor = System.Drawing.Color.Empty;
            stateProperties53.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSourceChannel.OnActiveState = stateProperties53;
            stateProperties54.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties54.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties54.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties54.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtSourceChannel.OnDisabledState = stateProperties54;
            stateProperties55.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties55.FillColor = System.Drawing.Color.Empty;
            stateProperties55.ForeColor = System.Drawing.Color.Empty;
            stateProperties55.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSourceChannel.OnHoverState = stateProperties55;
            stateProperties56.BorderColor = System.Drawing.Color.Silver;
            stateProperties56.FillColor = System.Drawing.Color.White;
            stateProperties56.ForeColor = System.Drawing.Color.Empty;
            stateProperties56.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSourceChannel.OnIdleState = stateProperties56;
            this.txtSourceChannel.Padding = new System.Windows.Forms.Padding(3);
            this.txtSourceChannel.PasswordChar = '\0';
            this.txtSourceChannel.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtSourceChannel.PlaceholderText = "Source Channel";
            this.txtSourceChannel.ReadOnly = false;
            this.txtSourceChannel.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSourceChannel.SelectedText = "";
            this.txtSourceChannel.SelectionLength = 0;
            this.txtSourceChannel.SelectionStart = 0;
            this.txtSourceChannel.ShortcutsEnabled = true;
            this.txtSourceChannel.Size = new System.Drawing.Size(301, 38);
            this.txtSourceChannel.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtSourceChannel.TabIndex = 4;
            this.txtSourceChannel.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtSourceChannel.TextMarginBottom = 0;
            this.txtSourceChannel.TextMarginLeft = 3;
            this.txtSourceChannel.TextMarginTop = 0;
            this.txtSourceChannel.TextPlaceholder = "Source Channel";
            this.txtSourceChannel.UseSystemPasswordChar = false;
            this.txtSourceChannel.WordWrap = true;
            // 
            // txtChannelEdit
            // 
            this.txtChannelEdit.AcceptsReturn = false;
            this.txtChannelEdit.AcceptsTab = false;
            this.txtChannelEdit.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.txtChannelEdit.AnimationSpeed = 200;
            this.txtChannelEdit.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtChannelEdit.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtChannelEdit.BackColor = System.Drawing.Color.Transparent;
            this.txtChannelEdit.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtChannelEdit.BackgroundImage")));
            this.txtChannelEdit.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtChannelEdit.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtChannelEdit.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtChannelEdit.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtChannelEdit.BorderRadius = 1;
            this.txtChannelEdit.BorderThickness = 1;
            this.txtChannelEdit.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtChannelEdit.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtChannelEdit.DefaultFont = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtChannelEdit.DefaultText = "";
            this.txtChannelEdit.Enabled = false;
            this.txtChannelEdit.FillColor = System.Drawing.Color.White;
            this.txtChannelEdit.HideSelection = true;
            this.txtChannelEdit.IconLeft = null;
            this.txtChannelEdit.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtChannelEdit.IconPadding = 10;
            this.txtChannelEdit.IconRight = null;
            this.txtChannelEdit.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtChannelEdit.Lines = new string[0];
            this.txtChannelEdit.Location = new System.Drawing.Point(6, 22);
            this.txtChannelEdit.MaxLength = 32767;
            this.txtChannelEdit.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtChannelEdit.Modified = false;
            this.txtChannelEdit.Multiline = false;
            this.txtChannelEdit.Name = "txtChannelEdit";
            stateProperties57.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties57.FillColor = System.Drawing.Color.Empty;
            stateProperties57.ForeColor = System.Drawing.Color.Empty;
            stateProperties57.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtChannelEdit.OnActiveState = stateProperties57;
            stateProperties58.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties58.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties58.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties58.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtChannelEdit.OnDisabledState = stateProperties58;
            stateProperties59.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties59.FillColor = System.Drawing.Color.Empty;
            stateProperties59.ForeColor = System.Drawing.Color.Empty;
            stateProperties59.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtChannelEdit.OnHoverState = stateProperties59;
            stateProperties60.BorderColor = System.Drawing.Color.Silver;
            stateProperties60.FillColor = System.Drawing.Color.White;
            stateProperties60.ForeColor = System.Drawing.Color.Empty;
            stateProperties60.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtChannelEdit.OnIdleState = stateProperties60;
            this.txtChannelEdit.Padding = new System.Windows.Forms.Padding(3);
            this.txtChannelEdit.PasswordChar = '\0';
            this.txtChannelEdit.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtChannelEdit.PlaceholderText = "Channel";
            this.txtChannelEdit.ReadOnly = false;
            this.txtChannelEdit.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtChannelEdit.SelectedText = "";
            this.txtChannelEdit.SelectionLength = 0;
            this.txtChannelEdit.SelectionStart = 0;
            this.txtChannelEdit.ShortcutsEnabled = true;
            this.txtChannelEdit.Size = new System.Drawing.Size(152, 38);
            this.txtChannelEdit.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtChannelEdit.TabIndex = 3;
            this.txtChannelEdit.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtChannelEdit.TextMarginBottom = 0;
            this.txtChannelEdit.TextMarginLeft = 3;
            this.txtChannelEdit.TextMarginTop = 0;
            this.txtChannelEdit.TextPlaceholder = "Channel";
            this.txtChannelEdit.UseSystemPasswordChar = false;
            this.txtChannelEdit.WordWrap = true;
            // 
            // btnStop
            // 
            this.btnStop.AllowAnimations = true;
            this.btnStop.AllowMouseEffects = true;
            this.btnStop.AllowToggling = false;
            this.btnStop.AnimationSpeed = 200;
            this.btnStop.AutoGenerateColors = false;
            this.btnStop.AutoRoundBorders = false;
            this.btnStop.AutoSizeLeftIcon = true;
            this.btnStop.AutoSizeRightIcon = true;
            this.btnStop.BackColor = System.Drawing.Color.Transparent;
            this.btnStop.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(57)))), ((int)(((byte)(63)))), ((int)(((byte)(68)))));
            this.btnStop.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnStop.BackgroundImage")));
            this.btnStop.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnStop.ButtonText = "Stop";
            this.btnStop.ButtonTextMarginLeft = 0;
            this.btnStop.ColorContrastOnClick = 45;
            this.btnStop.ColorContrastOnHover = 45;
            this.btnStop.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges11.BottomLeft = true;
            borderEdges11.BottomRight = true;
            borderEdges11.TopLeft = true;
            borderEdges11.TopRight = true;
            this.btnStop.CustomizableEdges = borderEdges11;
            this.btnStop.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnStop.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnStop.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnStop.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnStop.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnStop.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnStop.ForeColor = System.Drawing.Color.White;
            this.btnStop.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnStop.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnStop.IconLeftPadding = new System.Windows.Forms.Padding(3);
            this.btnStop.IconMarginLeft = 11;
            this.btnStop.IconPadding = 10;
            this.btnStop.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnStop.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnStop.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnStop.IconSize = 25;
            this.btnStop.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(57)))), ((int)(((byte)(63)))), ((int)(((byte)(68)))));
            this.btnStop.IdleBorderRadius = 5;
            this.btnStop.IdleBorderThickness = 1;
            this.btnStop.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(57)))), ((int)(((byte)(63)))), ((int)(((byte)(68)))));
            this.btnStop.IdleIconLeftImage = null;
            this.btnStop.IdleIconRightImage = null;
            this.btnStop.IndicateFocus = false;
            this.btnStop.Location = new System.Drawing.Point(342, 45);
            this.btnStop.Name = "btnStop";
            this.btnStop.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnStop.OnDisabledState.BorderRadius = 5;
            this.btnStop.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnStop.OnDisabledState.BorderThickness = 1;
            this.btnStop.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnStop.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnStop.OnDisabledState.IconLeftImage = null;
            this.btnStop.OnDisabledState.IconRightImage = null;
            this.btnStop.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnStop.onHoverState.BorderRadius = 5;
            this.btnStop.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnStop.onHoverState.BorderThickness = 1;
            this.btnStop.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnStop.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnStop.onHoverState.IconLeftImage = null;
            this.btnStop.onHoverState.IconRightImage = null;
            this.btnStop.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(57)))), ((int)(((byte)(63)))), ((int)(((byte)(68)))));
            this.btnStop.OnIdleState.BorderRadius = 5;
            this.btnStop.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnStop.OnIdleState.BorderThickness = 1;
            this.btnStop.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(57)))), ((int)(((byte)(63)))), ((int)(((byte)(68)))));
            this.btnStop.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnStop.OnIdleState.IconLeftImage = null;
            this.btnStop.OnIdleState.IconRightImage = null;
            this.btnStop.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnStop.OnPressedState.BorderRadius = 5;
            this.btnStop.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnStop.OnPressedState.BorderThickness = 1;
            this.btnStop.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnStop.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnStop.OnPressedState.IconLeftImage = null;
            this.btnStop.OnPressedState.IconRightImage = null;
            this.btnStop.Size = new System.Drawing.Size(80, 37);
            this.btnStop.TabIndex = 5;
            this.btnStop.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnStop.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnStop.TextMarginLeft = 0;
            this.btnStop.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnStop.UseDefaultRadiusAndThickness = true;
            this.btnStop.EnabledChanged += new System.EventHandler(this.btnStop_EnabledChanged);
            this.btnStop.Click += new System.EventHandler(this.btnStop_Click);
            // 
            // btnStart
            // 
            this.btnStart.AllowAnimations = true;
            this.btnStart.AllowMouseEffects = true;
            this.btnStart.AllowToggling = false;
            this.btnStart.AnimationSpeed = 200;
            this.btnStart.AutoGenerateColors = false;
            this.btnStart.AutoRoundBorders = false;
            this.btnStart.AutoSizeLeftIcon = true;
            this.btnStart.AutoSizeRightIcon = true;
            this.btnStart.BackColor = System.Drawing.Color.Transparent;
            this.btnStart.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(81)))), ((int)(((byte)(137)))));
            this.btnStart.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnStart.BackgroundImage")));
            this.btnStart.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnStart.ButtonText = "Start";
            this.btnStart.ButtonTextMarginLeft = 0;
            this.btnStart.ColorContrastOnClick = 45;
            this.btnStart.ColorContrastOnHover = 45;
            this.btnStart.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges12.BottomLeft = true;
            borderEdges12.BottomRight = true;
            borderEdges12.TopLeft = true;
            borderEdges12.TopRight = true;
            this.btnStart.CustomizableEdges = borderEdges12;
            this.btnStart.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnStart.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnStart.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnStart.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnStart.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnStart.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnStart.ForeColor = System.Drawing.Color.White;
            this.btnStart.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnStart.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnStart.IconLeftPadding = new System.Windows.Forms.Padding(3);
            this.btnStart.IconMarginLeft = 11;
            this.btnStart.IconPadding = 10;
            this.btnStart.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnStart.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnStart.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnStart.IconSize = 25;
            this.btnStart.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(81)))), ((int)(((byte)(137)))));
            this.btnStart.IdleBorderRadius = 5;
            this.btnStart.IdleBorderThickness = 1;
            this.btnStart.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(81)))), ((int)(((byte)(137)))));
            this.btnStart.IdleIconLeftImage = null;
            this.btnStart.IdleIconRightImage = null;
            this.btnStart.IndicateFocus = false;
            this.btnStart.Location = new System.Drawing.Point(256, 45);
            this.btnStart.Name = "btnStart";
            this.btnStart.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnStart.OnDisabledState.BorderRadius = 5;
            this.btnStart.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnStart.OnDisabledState.BorderThickness = 1;
            this.btnStart.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnStart.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnStart.OnDisabledState.IconLeftImage = null;
            this.btnStart.OnDisabledState.IconRightImage = null;
            this.btnStart.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnStart.onHoverState.BorderRadius = 5;
            this.btnStart.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnStart.onHoverState.BorderThickness = 1;
            this.btnStart.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnStart.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnStart.onHoverState.IconLeftImage = null;
            this.btnStart.onHoverState.IconRightImage = null;
            this.btnStart.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(81)))), ((int)(((byte)(137)))));
            this.btnStart.OnIdleState.BorderRadius = 5;
            this.btnStart.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnStart.OnIdleState.BorderThickness = 1;
            this.btnStart.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(81)))), ((int)(((byte)(137)))));
            this.btnStart.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnStart.OnIdleState.IconLeftImage = null;
            this.btnStart.OnIdleState.IconRightImage = null;
            this.btnStart.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnStart.OnPressedState.BorderRadius = 5;
            this.btnStart.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnStart.OnPressedState.BorderThickness = 1;
            this.btnStart.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnStart.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnStart.OnPressedState.IconLeftImage = null;
            this.btnStart.OnPressedState.IconRightImage = null;
            this.btnStart.Size = new System.Drawing.Size(80, 37);
            this.btnStart.TabIndex = 4;
            this.btnStart.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnStart.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnStart.TextMarginLeft = 0;
            this.btnStart.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnStart.UseDefaultRadiusAndThickness = true;
            this.btnStart.EnabledChanged += new System.EventHandler(this.btnStart_EnabledChanged);
            this.btnStart.Click += new System.EventHandler(this.btnStart_Click);
            // 
            // txtTimer
            // 
            this.txtTimer.AcceptsReturn = false;
            this.txtTimer.AcceptsTab = false;
            this.txtTimer.AnimationSpeed = 200;
            this.txtTimer.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtTimer.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtTimer.BackColor = System.Drawing.Color.Transparent;
            this.txtTimer.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtTimer.BackgroundImage")));
            this.txtTimer.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtTimer.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtTimer.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtTimer.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtTimer.BorderRadius = 1;
            this.txtTimer.BorderThickness = 1;
            this.txtTimer.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTimer.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTimer.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtTimer.DefaultText = "2";
            this.txtTimer.FillColor = System.Drawing.Color.White;
            this.txtTimer.HideSelection = true;
            this.txtTimer.IconLeft = null;
            this.txtTimer.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTimer.IconPadding = 10;
            this.txtTimer.IconRight = null;
            this.txtTimer.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTimer.Lines = new string[] {
        "2"};
            this.txtTimer.Location = new System.Drawing.Point(12, 45);
            this.txtTimer.MaxLength = 32767;
            this.txtTimer.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtTimer.Modified = false;
            this.txtTimer.Multiline = false;
            this.txtTimer.Name = "txtTimer";
            stateProperties41.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties41.FillColor = System.Drawing.Color.Empty;
            stateProperties41.ForeColor = System.Drawing.Color.Empty;
            stateProperties41.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTimer.OnActiveState = stateProperties41;
            stateProperties42.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties42.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties42.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties42.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtTimer.OnDisabledState = stateProperties42;
            stateProperties43.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties43.FillColor = System.Drawing.Color.Empty;
            stateProperties43.ForeColor = System.Drawing.Color.Empty;
            stateProperties43.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTimer.OnHoverState = stateProperties43;
            stateProperties44.BorderColor = System.Drawing.Color.Silver;
            stateProperties44.FillColor = System.Drawing.Color.White;
            stateProperties44.ForeColor = System.Drawing.Color.Empty;
            stateProperties44.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTimer.OnIdleState = stateProperties44;
            this.txtTimer.Padding = new System.Windows.Forms.Padding(3);
            this.txtTimer.PasswordChar = '\0';
            this.txtTimer.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtTimer.PlaceholderText = "Timer (Minutes)";
            this.txtTimer.ReadOnly = false;
            this.txtTimer.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtTimer.SelectedText = "";
            this.txtTimer.SelectionLength = 0;
            this.txtTimer.SelectionStart = 0;
            this.txtTimer.ShortcutsEnabled = true;
            this.txtTimer.Size = new System.Drawing.Size(152, 38);
            this.txtTimer.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtTimer.TabIndex = 2;
            this.txtTimer.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtTimer.TextMarginBottom = 0;
            this.txtTimer.TextMarginLeft = 3;
            this.txtTimer.TextMarginTop = 0;
            this.txtTimer.TextPlaceholder = "Timer (Minutes)";
            this.txtTimer.UseSystemPasswordChar = false;
            this.txtTimer.WordWrap = true;
            // 
            // btnSetTimer
            // 
            this.btnSetTimer.AllowAnimations = true;
            this.btnSetTimer.AllowMouseEffects = true;
            this.btnSetTimer.AllowToggling = false;
            this.btnSetTimer.AnimationSpeed = 200;
            this.btnSetTimer.AutoGenerateColors = false;
            this.btnSetTimer.AutoRoundBorders = false;
            this.btnSetTimer.AutoSizeLeftIcon = true;
            this.btnSetTimer.AutoSizeRightIcon = true;
            this.btnSetTimer.BackColor = System.Drawing.Color.Transparent;
            this.btnSetTimer.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(206)))), ((int)(((byte)(212)))), ((int)(((byte)(218)))));
            this.btnSetTimer.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSetTimer.BackgroundImage")));
            this.btnSetTimer.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSetTimer.ButtonText = "Set Timer";
            this.btnSetTimer.ButtonTextMarginLeft = 0;
            this.btnSetTimer.ColorContrastOnClick = 45;
            this.btnSetTimer.ColorContrastOnHover = 45;
            this.btnSetTimer.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges13.BottomLeft = true;
            borderEdges13.BottomRight = true;
            borderEdges13.TopLeft = true;
            borderEdges13.TopRight = true;
            this.btnSetTimer.CustomizableEdges = borderEdges13;
            this.btnSetTimer.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSetTimer.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSetTimer.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSetTimer.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSetTimer.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSetTimer.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSetTimer.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(81)))), ((int)(((byte)(137)))));
            this.btnSetTimer.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSetTimer.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSetTimer.IconLeftPadding = new System.Windows.Forms.Padding(3);
            this.btnSetTimer.IconMarginLeft = 11;
            this.btnSetTimer.IconPadding = 10;
            this.btnSetTimer.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSetTimer.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSetTimer.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSetTimer.IconSize = 25;
            this.btnSetTimer.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(206)))), ((int)(((byte)(212)))), ((int)(((byte)(218)))));
            this.btnSetTimer.IdleBorderRadius = 5;
            this.btnSetTimer.IdleBorderThickness = 1;
            this.btnSetTimer.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(206)))), ((int)(((byte)(212)))), ((int)(((byte)(218)))));
            this.btnSetTimer.IdleIconLeftImage = null;
            this.btnSetTimer.IdleIconRightImage = null;
            this.btnSetTimer.IndicateFocus = false;
            this.btnSetTimer.Location = new System.Drawing.Point(170, 45);
            this.btnSetTimer.Name = "btnSetTimer";
            this.btnSetTimer.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSetTimer.OnDisabledState.BorderRadius = 5;
            this.btnSetTimer.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSetTimer.OnDisabledState.BorderThickness = 1;
            this.btnSetTimer.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSetTimer.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSetTimer.OnDisabledState.IconLeftImage = null;
            this.btnSetTimer.OnDisabledState.IconRightImage = null;
            this.btnSetTimer.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnSetTimer.onHoverState.BorderRadius = 5;
            this.btnSetTimer.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSetTimer.onHoverState.BorderThickness = 1;
            this.btnSetTimer.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnSetTimer.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSetTimer.onHoverState.IconLeftImage = null;
            this.btnSetTimer.onHoverState.IconRightImage = null;
            this.btnSetTimer.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(206)))), ((int)(((byte)(212)))), ((int)(((byte)(218)))));
            this.btnSetTimer.OnIdleState.BorderRadius = 5;
            this.btnSetTimer.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSetTimer.OnIdleState.BorderThickness = 1;
            this.btnSetTimer.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(206)))), ((int)(((byte)(212)))), ((int)(((byte)(218)))));
            this.btnSetTimer.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(81)))), ((int)(((byte)(137)))));
            this.btnSetTimer.OnIdleState.IconLeftImage = null;
            this.btnSetTimer.OnIdleState.IconRightImage = null;
            this.btnSetTimer.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSetTimer.OnPressedState.BorderRadius = 5;
            this.btnSetTimer.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSetTimer.OnPressedState.BorderThickness = 1;
            this.btnSetTimer.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSetTimer.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSetTimer.OnPressedState.IconLeftImage = null;
            this.btnSetTimer.OnPressedState.IconRightImage = null;
            this.btnSetTimer.Size = new System.Drawing.Size(80, 37);
            this.btnSetTimer.TabIndex = 1;
            this.btnSetTimer.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSetTimer.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSetTimer.TextMarginLeft = 0;
            this.btnSetTimer.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSetTimer.UseDefaultRadiusAndThickness = true;
            this.btnSetTimer.Click += new System.EventHandler(this.btnSetTimer_Click);
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(81)))), ((int)(((byte)(137)))));
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.btnMaximize);
            this.bunifuPanel1.Controls.Add(this.btnMinimize);
            this.bunifuPanel1.Controls.Add(this.btnClose);
            this.bunifuPanel1.Cursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(1416, 39);
            this.bunifuPanel1.TabIndex = 0;
            // 
            // btnMaximize
            // 
            this.btnMaximize.ActiveImage = global::SimpleCopy.Properties.Resources.icons8_square_90;
            this.btnMaximize.AllowAnimations = true;
            this.btnMaximize.AllowBuffering = false;
            this.btnMaximize.AllowToggling = false;
            this.btnMaximize.AllowZooming = false;
            this.btnMaximize.AllowZoomingOnFocus = false;
            this.btnMaximize.Anchor = System.Windows.Forms.AnchorStyles.Right;
            this.btnMaximize.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(81)))), ((int)(((byte)(137)))));
            this.btnMaximize.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnMaximize.ErrorImage = ((System.Drawing.Image)(resources.GetObject("btnMaximize.ErrorImage")));
            this.btnMaximize.FadeWhenInactive = false;
            this.btnMaximize.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.btnMaximize.Image = global::SimpleCopy.Properties.Resources.icons8_square_90;
            this.btnMaximize.ImageActive = global::SimpleCopy.Properties.Resources.icons8_square_90;
            this.btnMaximize.ImageLocation = null;
            this.btnMaximize.ImageMargin = 15;
            this.btnMaximize.ImageSize = new System.Drawing.Size(18, 19);
            this.btnMaximize.ImageZoomSize = new System.Drawing.Size(33, 34);
            this.btnMaximize.InitialImage = ((System.Drawing.Image)(resources.GetObject("btnMaximize.InitialImage")));
            this.btnMaximize.Location = new System.Drawing.Point(1333, 2);
            this.btnMaximize.Name = "btnMaximize";
            this.btnMaximize.Rotation = 0;
            this.btnMaximize.ShowActiveImage = true;
            this.btnMaximize.ShowCursorChanges = true;
            this.btnMaximize.ShowImageBorders = false;
            this.btnMaximize.ShowSizeMarkers = false;
            this.btnMaximize.Size = new System.Drawing.Size(33, 34);
            this.btnMaximize.TabIndex = 2;
            this.btnMaximize.ToolTipText = "";
            this.btnMaximize.WaitOnLoad = false;
            this.btnMaximize.Zoom = 15;
            this.btnMaximize.ZoomSpeed = 10;
            this.btnMaximize.Click += new System.EventHandler(this.btnMaximize_Click);
            // 
            // btnMinimize
            // 
            this.btnMinimize.ActiveImage = global::SimpleCopy.Properties.Resources.icons8_subtract_100;
            this.btnMinimize.AllowAnimations = true;
            this.btnMinimize.AllowBuffering = false;
            this.btnMinimize.AllowToggling = false;
            this.btnMinimize.AllowZooming = false;
            this.btnMinimize.AllowZoomingOnFocus = false;
            this.btnMinimize.Anchor = System.Windows.Forms.AnchorStyles.Right;
            this.btnMinimize.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(81)))), ((int)(((byte)(137)))));
            this.btnMinimize.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnMinimize.ErrorImage = ((System.Drawing.Image)(resources.GetObject("btnMinimize.ErrorImage")));
            this.btnMinimize.FadeWhenInactive = false;
            this.btnMinimize.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.btnMinimize.Image = global::SimpleCopy.Properties.Resources.icons8_subtract_100;
            this.btnMinimize.ImageActive = global::SimpleCopy.Properties.Resources.icons8_subtract_100;
            this.btnMinimize.ImageLocation = null;
            this.btnMinimize.ImageMargin = 5;
            this.btnMinimize.ImageSize = new System.Drawing.Size(28, 29);
            this.btnMinimize.ImageZoomSize = new System.Drawing.Size(33, 34);
            this.btnMinimize.InitialImage = ((System.Drawing.Image)(resources.GetObject("btnMinimize.InitialImage")));
            this.btnMinimize.Location = new System.Drawing.Point(1289, 3);
            this.btnMinimize.Name = "btnMinimize";
            this.btnMinimize.Rotation = 0;
            this.btnMinimize.ShowActiveImage = true;
            this.btnMinimize.ShowCursorChanges = true;
            this.btnMinimize.ShowImageBorders = false;
            this.btnMinimize.ShowSizeMarkers = false;
            this.btnMinimize.Size = new System.Drawing.Size(33, 34);
            this.btnMinimize.TabIndex = 1;
            this.btnMinimize.ToolTipText = "";
            this.btnMinimize.WaitOnLoad = false;
            this.btnMinimize.Zoom = 5;
            this.btnMinimize.ZoomSpeed = 10;
            this.btnMinimize.Click += new System.EventHandler(this.btnMinimize_Click);
            // 
            // btnClose
            // 
            this.btnClose.ActiveImage = global::SimpleCopy.Properties.Resources.icons8_multiply_100;
            this.btnClose.AllowAnimations = true;
            this.btnClose.AllowBuffering = false;
            this.btnClose.AllowToggling = false;
            this.btnClose.AllowZooming = true;
            this.btnClose.AllowZoomingOnFocus = false;
            this.btnClose.Anchor = System.Windows.Forms.AnchorStyles.Right;
            this.btnClose.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(81)))), ((int)(((byte)(137)))));
            this.btnClose.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnClose.ErrorImage = ((System.Drawing.Image)(resources.GetObject("btnClose.ErrorImage")));
            this.btnClose.FadeWhenInactive = false;
            this.btnClose.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.btnClose.Image = global::SimpleCopy.Properties.Resources.icons8_multiply_100;
            this.btnClose.ImageActive = global::SimpleCopy.Properties.Resources.icons8_multiply_100;
            this.btnClose.ImageLocation = null;
            this.btnClose.ImageMargin = 5;
            this.btnClose.ImageSize = new System.Drawing.Size(28, 29);
            this.btnClose.ImageZoomSize = new System.Drawing.Size(33, 34);
            this.btnClose.InitialImage = ((System.Drawing.Image)(resources.GetObject("btnClose.InitialImage")));
            this.btnClose.Location = new System.Drawing.Point(1373, 3);
            this.btnClose.Name = "btnClose";
            this.btnClose.Rotation = 0;
            this.btnClose.ShowActiveImage = true;
            this.btnClose.ShowCursorChanges = true;
            this.btnClose.ShowImageBorders = false;
            this.btnClose.ShowSizeMarkers = false;
            this.btnClose.Size = new System.Drawing.Size(33, 34);
            this.btnClose.TabIndex = 0;
            this.btnClose.ToolTipText = "";
            this.btnClose.WaitOnLoad = false;
            this.btnClose.Zoom = 5;
            this.btnClose.ZoomSpeed = 10;
            this.btnClose.Click += new System.EventHandler(this.btnClose_Click);
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(243)))), ((int)(((byte)(249)))));
            this.ClientSize = new System.Drawing.Size(1416, 673);
            this.Controls.Add(this.bunifuGroupBox2);
            this.Controls.Add(this.bunifuGroupBox1);
            this.Controls.Add(this.btnStop);
            this.Controls.Add(this.btnStart);
            this.Controls.Add(this.dataGridView1);
            this.Controls.Add(this.txtTimer);
            this.Controls.Add(this.btnSetTimer);
            this.Controls.Add(this.bunifuPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "Form1";
            this.Text = "Form1";
            this.Load += new System.EventHandler(this.Form1_Load);
            ((System.ComponentModel.ISupportInitialize)(this.dataGridView1)).EndInit();
            this.bunifuGroupBox1.ResumeLayout(false);
            this.bunifuGroupBox2.ResumeLayout(false);
            this.bunifuPanel1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion
        private Bunifu.Framework.UI.BunifuDragControl bunifuDragControl1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuImageButton btnClose;
        private Bunifu.UI.WinForms.BunifuImageButton btnMinimize;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSetTimer;
        private Bunifu.UI.WinForms.BunifuTextBox txtTimer;
        private System.Windows.Forms.DataGridView dataGridView1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnStart;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnStop;
        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnClear;
        private Bunifu.UI.WinForms.BunifuTextBox txtDestinationChannel;
        private Bunifu.UI.WinForms.BunifuTextBox txtSourceChannel;
        private Bunifu.UI.WinForms.BunifuTextBox txtChannelEdit;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnUpdate;
        public Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuFormDock bunifuFormDock1;
        private System.Windows.Forms.DataGridViewTextBoxColumn Channel;
        private System.Windows.Forms.DataGridViewTextBoxColumn SourceChannel;
        private System.Windows.Forms.DataGridViewTextBoxColumn DestinationChannel;
        private System.Windows.Forms.DataGridViewCheckBoxColumn Running;
        private Bunifu.UI.WinForms.BunifuCheckBox chkRunning;
        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox2;
        private Bunifu.UI.WinForms.BunifuTextBox txtLogs;
        private Bunifu.UI.WinForms.BunifuImageButton btnMaximize;
    }
}

